version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  
  gateway:
    image: streamsforlab/gateway:dev
    restart: always
    expose:
      - "8000"
    environment:
      - VIRTUAL_HOST=streamsforlab.gateway.bucaramanga.upb.edu.co,www.streamsforlab.gateway.bucaramanga.upb.edu.co
  client:
    image: streamsforlab/client:dev
    restart: always
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=streamsforlab.bucaramanga.upb.edu.co,www.streamsforlab.bucaramanga.upb.edu.co   